### Deploy Debezium Connector
curl -X POST \
  -H "Content-Type: application/json" \
  --data @postgres.config.json \
  http://localhost:8083/connectors


### Verify the connector is running
curl -X GET http://localhost:8083/connectors/postgres_connector/status
